# Generated by Django 2.1.1 on 2018-10-04 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rcs_sensitivity.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RCSSen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(null=True)),
                ('date_insert', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_init', models.DateTimeField(null=True, verbose_name='Fecha de inicio')),
                ('date_end', models.DateTimeField(null=True, verbose_name='Fecha de fin')),
                ('estatus', models.IntegerField(choices=[(1, 'Pendiente'), (4, 'Fallido'), (2, 'En Proceso'), (3, 'Finalizado')], default=1)),
                ('fecha_corte', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero_escenarios', models.IntegerField(null=True)),
                ('sim', models.FileField(blank=True, null=True, upload_to=rcs_sensitivity.models.user_directory_path, verbose_name='SIM.mat')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rcs_sen_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultRCSSen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(null=True)),
                ('path', models.CharField(max_length=100)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('rcs_sen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rcs', to='rcs_sensitivity.RCSSen')),
            ],
        ),
    ]
