# Generated by Django 2.1.1 on 2018-10-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcs_sensitivity', '0002_auto_20181004_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultrcssen',
            name='zip_file',
            field=models.CharField(default='sin path', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rcssen',
            name='estatus',
            field=models.IntegerField(choices=[(3, 'Finalizado'), (1, 'Pendiente'), (4, 'Fallido'), (2, 'En Proceso')], default=1),
        ),
        migrations.AlterField(
            model_name='resultrcssen',
            name='path',
            field=models.CharField(max_length=200),
        ),
    ]
